image: Visual Studio 2019

environment:
  matrix:
  - solution_path: Lab7\Task2\WebScraper.sln

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab7\Task2\WebScraper.Tests\WebScraper.Tests.fsproj
