image: Visual Studio 2019

environment:
  matrix:
  - solution_path: Lab6\Task1\WorkflowCalculator\WorkflowCalculator.sln

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab6\Task1\WorkflowCalculator.Tests\WorkflowCalculator.Tests.fsproj
