image: Visual Studio 2019

environment:
  matrix:
  - solution_path: Lab4\Task1\BracketBalance\BracketBalance.sln

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
   dotnet test --test-adapter-path:. --logger:Appveyor Lab4\Task1\BracketBalance.Tests\BracketBalance.Tests.fsproj
