image: Visual Studio 2019

environment:
  matrix:
  - solution_path: Lab3\Task3\LambdaInterpreter\LambdaInterpreter.sln

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab3\Task3\LambdaInterpreter.Tests\LambdaInterpreter.Tests.fsproj
