image: Visual Studio 2019

environment:
  matrix:
  - solution_path: Lab1\Factorial\Factorial.sln

before_build:
  - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab1\Factorial.Tests\Factorial.Tests.fsproj