image: Visual Studio 2019

environment:
  matrix:
  - solution_path: Lab8\SyntaxAnalyzer.sln

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab8\SyntaxAnalyzer.Tests\SyntaxAnalyzer.Tests.fsproj
