image: Visual Studio 2019

environment:
  matrix:
  - solution_path: Lab1\Task1\Factorial\Factorial.sln
  - solution_path: Lab1\Task2\Fibonacci\Fibonacci.sln
  - solution_path: Lab1\Task3\ReverseList\ReverseList.sln
  - solution_path: Lab1\Task4\CreateList\CreateList.sln
  - solution_path: Lab1\Task5\FirstEntry\FirstEntry.sln
  - solution_path: Lab2\Task1\EvenCount\EvenCount.sln
  - solution_path: Lab2\Task2\BTreeMap\BTreeMap.sln

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab1\Task1\Factorial.Tests\Factorial.Tests.fsproj
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab1\Task2\Fibonacci.Tests\Fibonacci.Tests.fsproj
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab1\Task3\ReverseList.Tests\ReverseList.Tests.fsproj
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab1\Task4\CreateList.Tests\CreateList.Tests.fsproj
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab1\Task5\FirstEntry.Tests\FirstEntry.Tests.fsproj
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab2\Task1\EvenCount.Tests\EvenCount.Tests.fsproj
  - dotnet test --test-adapter-path:. --logger:Appveyor Lab2\Task2\BTreeMap.Tests\BTreeMap.Tests.fsproj
